### ISSUE TITLE
Server Requirements

### ISSUE THREAD

**Issue by mx1010** [MyHush/hushwebminer#4]
Is it safe to assume a basic web server - centos, apache, mysql, php is adequate?

Can anyone provide an overview of the requirements?

**Comment by leto** [comment]
@mx1010 great question! I will add this to the README.

For now, all you need is Perl 5.8 or higher as your system Perl, which just about every operating system has these days.

No apache is required, no mysql, no php is required. I *do* use nginx in production to proxy requests, because I am planning on scaling up. It is not necessary for normal use.

Just so you understand, the `server.pl` in this repo implements it's own HTTP server, which is why nothing else is needed. It can serve static files and handle WebSocket connections.

I do plan on making Redis a dependency in the future, maybe optional.
